export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_FAIL = "GET_SINGLE_USER_FAIL";


export const GIVE_PERMISSION = "GIVE_PERMISSION";
export const GIVE_PERMISSION_SUCCESS = "GIVE_PERMISSION_SUCCESS";
export const GIVE_PERMISSION_FAIL = "GIVE_PERMISSION_FAIL";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";

export const GENERATE_URL = "GENERATE_URL";
export const GENERATE_URL_SUCCESS = "GENERATE_URL_SUCCESS";
export const GENERATE_URL_FAIL = "GENERATE_URL_FAIL";

export const GENERATE_FITBIT_DATA = "GENERATE_FITBIT_DATA";
export const GENERATE_FITBIT_DATA_SUCCESS = "GENERATE_FITBIT_DATA_SUCCESS";
export const GENERATE_FITBIT_DATA_FAIL = "GENERATE_FITBIT_DATA_FAIL";

export const GET_ACTIVITY_DATA = "GET_ACTIVITY_DATA";
export const GET_ACTIVITY_DATA_SUCCESS = "GET_ACTIVITY_DATA_SUCCESS";
export const GET_ACTIVITY_DATA_FAIL = "GET_ACTIVITY_DATA_FAIL";

export const POST_USER_DATA = "POST_USER_DATA";
export const POST_USER_DATA_SUCCESS = "POST_USER_DATA_SUCCESS";
export const POST_USER_DATA_FAIL = "POST_USER_DATA_FAIL";


export const POST_HEART_DATA = "POST_HEART_DATA";
export const POST_HEART_DATA_SUCCESS = "POST_HEART_DATA_SUCCESS";
export const POST_HEART_DATA_FAIL = "POST_HEART_DATA_FAIL";

export const EXTEND_TOKEN = "EXTEND_TOKEN";
export const EXTEND_TOKEN_SUCCESS = "EXTEND_TOKEN_SUCCESS";
export const EXTEND_TOKEN_FAIL = "EXTEND_TOKEN_FAIL";

//EDIT USER
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const STORE_USER_DATA = "STORE_USER_DATA";

export const STORE_USER_LOADING = "STORE_USER_LOADING";
