
//registration
export const REGISTRATION_USER = "REGISTRATION_USER"
export const REGISTRATION_USER_SUCCESS = "REGISTRATION_USER_SUCCESS"
export const REGISTRATION_USER_FAIL = "REGISTRATION_USER_FAIL"

//RESET PASSWORD
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"