export const GET_DASHBOARD_HEART_DATA = "GET_DASHBOARD_HEART_DATA";
export const GET_DASHBOARD_HEART_DATA_SUCCESS = "GET_DASHBOARD_HEART_DATA_SUCCESS";
export const GET_DASHBOARD_HEART_DATA_FAIL = "GET_DASHBOARD_HEART_DATA_FAIL";

export const GET_DASHBOARD_STEP_DATA = "GET_DASHBOARD_STEP_DATA";
export const GET_DASHBOARD_STEP_DATA_SUCCESS = "GET_DASHBOARD_STEP_DATA_SUCCESS";
export const GET_DASHBOARD_STEP_DATA_FAIL = "GET_DASHBOARD_STEP_DATA_FAIL";


export const GET_DASHBOARD_CALORIES_DATA = "GET_DASHBOARD_CALORIES_DATA";
export const GET_DASHBOARD_CALORIES_DATA_SUCCESS = "GET_DASHBOARD_CALORIES_DATA_SUCCESS";
export const GET_DASHBOARD_CALORIES_DATA_FAIL = "GET_DASHBOARD_CALORIES_DATA_FAIL";

export const GET_DASHBOARD_DISTANCE_DATA = "GET_DASHBOARD_DISTANCE_DATA";
export const GET_DASHBOARD_DISTANCE_DATA_SUCCESS = "GET_DASHBOARD_DISTANCE_DATA_SUCCESS";
export const GET_DASHBOARD_DISTANCE_DATA_FAIL = "GET_DASHBOARD_DISTANCE_DATA_FAIL";

export const GET_DASHBOARD_FLOOR_DATA = "GET_DASHBOARD_FLOOR_DATA";
export const GET_DASHBOARD_FLOOR_DATA_SUCCESS = "GET_DASHBOARD_FLOOR_DATA_SUCCESS";
export const GET_DASHBOARD_FLOOR_DATA_FAIL = "GET_DASHBOARD_FLOOR_DATA_FAIL";

export const GET_DASHBOARD_ELEVATION_DATA = "GET_DASHBOARD_ELEVATION_DATA";
export const GET_DASHBOARD_ELEVATION_DATA_SUCCESS = "GET_DASHBOARD_ELEVATION_DATA_SUCCESS";
export const GET_DASHBOARD_ELEVATION_DATA_FAIL = "GET_DASHBOARD_ELEVATION_DATA_FAIL";
export const STORE_DASHBOARD_DATA = "STORE_DASHBOARD_DATA";